### ISSUE TITLE
wine-mono installation

### ISSUE THREAD

**Issue by hcfw007** [huan/docker-wine#5]
I understand the latest version of docker-wine builds no longer contain wine-mono, but the installation methods you used to use seems to be problematic.
We use your docker-windows image to run Wecom, and inside that image, I ran `wine uninstaller` to check installed packages, and I did not find wine-mono.
Also according to official website and wine-mono download server, you should contain system architecture in both url and downloaded file name for installation.
So in docker file, if you want to put wine-mono back someday, you might want to change
`curl -sL -o /usr/share/wine/mono/wine-mono-${MONO_VER}.msi \
    "https://dl.winehq.org/wine/wine-mono/${MONO_VER}/wine-mono-${MONO_VER}.msi"`
to
`curl -sL -o /usr/share/wine/mono/wine-mono-${MONO_VER}-x86.msi \
    "https://dl.winehq.org/wine/wine-mono/${MONO_VER}/wine-mono-${MONO_VER}-x86.msi" \`

**Comment by hcfw007** [comment]
I can find wine-mono package in `wine uninstaller` with Installation in this way.

**Comment by huan** [comment]
Thanks for sharing and filing this issue.

It would be highly appreciate if you can send a Pull Request to demonstrate how to fix it.
